apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-volumes-size
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
            - name: couchdb-k8s-stress-tests
              image: gitlab-registry.caligrafix.cl:443/ecaligrafix/couchdb-k8s-stress-tests:latest
              args: ["--script", "0"]
              envFrom:
                - secretRef:
                    name: couchdb-couchdb
          restartPolicy: Never
          imagePullSecrets:
          - name: registry-credentials