apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: pvc-editor
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing PersistentVolumeClaim 
  # objects is "persistentvolumeclaims"
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "update", "patch", "delete", "watch", "list"]



